Fix -Wbitwise-instead-of-logical
Bug: http://b/215753485

Reported by clang-r445002

error: use of bitwise '|' with boolean operands [-Werro
r,-Wbitwise-instead-of-logical]

  if (gnssCbIface != nullptr || gnssCbIface_2_0 != nullptr| gnssCbIface_2_1 != nullptr) {
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                          ||

Test: build with clang-r445002
Change-Id: I9410eb5208227dd70bd036aee02fb2aeb912f266
Merged-In: I9410eb5208227dd70bd036aee02fb2aeb912f266

(cherry picked from commit 1f2470e50f22404143d283bdcc35c52f2c97ba13)

Change-Id: I9f8ca9556e0f794feb405b042f73274d4be7e730